;----------------------------------------------------------
;Automatically generated by AutoHotkey. You can ignore that, but you should keep it nonetheless.
;----------------------------------------------------------
#NoEnv  ; Recommended for performance and compatibility with future AutoHotkey releases.
; #Warn  ; Enable warnings to assist with detecting common errors.
SendMode Input  ; Recommended for new scripts due to its superior speed and reliability.
SetWorkingDir %A_ScriptDir%  ; Ensures a consistent starting directory.
;----------------------------------------------------------

;----------------------------------------------------------
;Carl-bot's TagScript IntelliSense/Macro Script by Asty' and LPB
;Based on the blocks at: https://docs.carl.gg/tags-and-triggers/tags-advanced-Keyword/
;----------------------------------------------------------

;---------------------------------
;Command Block
;---------------------------------
Hotstring( ":xc*:`{c`:", "commandblock")
Return

commandblock:
SendRaw, {c:}
Send {left}
Return

;---------------------------------
;Discord Objects
;---------------------------------

; --- {user} Object ---
:c*:{user::
SendRaw {user}
return

:c*:{uav::
SendRaw {user(avatar)}
return

:c*:{uid::
SendRaw {user(id)}
return

:c*:{umen::
SendRaw {user(mention)}
return

:c*:{ucat::
SendRaw {user(created_at)}
return

:c*:{ujat::
SendRaw {user(joined_at)}
return

:c*:{uco::
SendRaw {user(color)}
return

:c*:{uname::
SendRaw {user(name)}
return

:c*:{uprop::
SendRaw {user(proper)}
return

:c*:{uroles::
SendRaw {user(roleids)}
return

:c*:{urid::
SendRaw {user(roleids)}
return

:c*:{upos::
SendRaw {user(position)}
return

; --- {target} Object ---
:c*:{tar::
SendRaw {target}
return

:c*:{tav::
SendRaw {target(avatar)}
return

:c*:{tid::
SendRaw {target(id)}
return

:c*:{tm::
SendRaw {target(mention)}
return

:c*:{tcat::
SendRaw {target(created_at)}
return

:c*:{tjat::
SendRaw {target(joined_at)}
return

:c*:{tco::
SendRaw {target(color)}
return

:c*:{tname::
SendRaw {target(name)}
return

:c*:{tprop::
SendRaw {target(proper)}
return

:c*:{troles::
SendRaw {target(roleids)}
return

:c*:{trid::
SendRaw {target(roleids)}
return

:c*:{tpos::
SendRaw {target(position)}
return

; --- {server} Object---
:c*:{ser::
SendRaw {server}
return

:c*:{sic::
SendRaw {server(icon)}
return

:c*:{sav::
SendRaw {server(icon)}
return

:c*:{sid::
SendRaw {server(id)}
return

:c*:{sown::
SendRaw {server(owner)}
return

:c*:{sran::
SendRaw {server(random)}
return

:c*:{smem::
SendRaw {server(members)}
return

:c*:{shum::
SendRaw {server(humans)}
return

:c*:{sro::
SendRaw {server(roles)}
return

:c*:{sch::
SendRaw {server(channels)}
return

:c*:{scat::
SendRaw {server(created_at)}
return

; --- {channel} Object ---
:c*:{chan::
SendRaw {channel}
return

:c*:{cid::
SendRaw {channel(id)}
return

:c*:{ct::
SendRaw {channel(topic)}
return

:c*:{csm::
SendRaw {channel(slowmode)}
return

:c*:{cpos::
SendRaw {channel(position)}
return

:c*:{cm::
SendRaw {channel(mention)}
return

;---------------------------------
;Action Blocks
;---------------------------------

:c*:{del::
SendRaw {delete}
return

:c*:{sil::
SendRaw {silence}
return

:c*:{ov::
SendRaw {override}
return

;---------------------------------
;Redirection Blocks
;---------------------------------

:c*:{dm::
SendRaw {dm}
return

:c*:{red::
SendRaw {redirect:}
Send {left}
return

;---------------------------------
;Use Limiting Blocks
;---------------------------------

:c*:{req::
SendRaw {require():}
Send {left 3}
return

:c*:{bl::
SendRaw {blacklist():}
Send {left 3}
return

;---------------------------------
;Reaction Blocks
;---------------------------------

:c*:{rea::
SendRaw {react: }
Send {left}
return

:c*:{reu::
SendRaw {reactu: }
Send {left}
return

;---------------------------------
;Specific Command Blocks
;---------------------------------

:c*:{crole:: ; Command Role - Role User ID Block
SendRaw {c:role {user(id)} }
Send {left}
return

:c*:{cra:: ; Command Role Add - Role Add User ID Block
SendRaw {c:role add {user(id)} }
Send {left}
return

:c*:{crt:: ;  Command Role Target - Role Add Target ID Block
SendRaw {c:role add {target(id)} }
Send {left}
return

:c*:{crc:: ; Command Role Custom
SendRaw {c:role custom {user(id)} }
Send {left}
return

:c*:{cec:: ; Command Echo
SendRaw {c:echo }
Send {left}
return

:c*:{cem:: ; Command Cembed
SendRaw {c:cembed }
Send {left}
return

;---------------------------------
;Condition Blocks
;---------------------------------

:c*:{if::
SendRaw {if():}
Send {left 3}
return

:c*:{any::
SendRaw {any(|):}
Send {left 4}
return

:c*:{or::
SendRaw {or(|):}
Send {left 4}
return

:c*:{all::
SendRaw {and(|):}
Send {left 4}
return

:c*:{and::
SendRaw {and(|):}
Send, {left 4}
return

:c*:{break::
SendRaw {break():}
Send {left 3}
return

;---------------------------------
;Variable Blocks (Data Storage)
;---------------------------------

:c*:{=::
SendRaw {=():}
Send {left 3}
return

:c*:{var::
SendRaw {=():}
Send {left 3}
return

:c*:{let::
SendRaw {=():}
Send {left 3}
return

;---------------------------------
;Arguments (Parsing)
;---------------------------------

:c*:{arg(::
SendRaw {args()}
Send {left 2}
return

:c*:{args::
SendRaw {args}
return

;---------------------------------
;List and Cycle Blocks
;---------------------------------

:c*:{li::
SendRaw {list():}
Send {left 3}
return

:c*:{cy::
SendRaw {cycle():}
Send {left 3}
return

:c*:{dex::
SendRaw {index():}
Send {left 3}
return

;---------------------------------
;Membership Test Operations (In and Contains)
;---------------------------------

:c*:{in::
SendRaw {in():}
Send {left 3}
return

:c*:{con::
SendRaw {contains():}
Send {left 3}
return

;---------------------------------
;Embed Blocks
;---------------------------------

:c*:{emt::
SendRaw {embed(title):}
Send {left}
return

:c*:{emu::
SendRaw {embed(url):}
Send {left}
return

:c*:{emd::
SendRaw {embed(description):}
Send {left}
return

:c*:{emc::
SendRaw {embed(color):#}
Send {left}
return

:c*:{emn::
SendRaw {embed(timestamp):now}
Send {left}
return

;---------------------------------
;Math Blocks
;---------------------------------

; --- Basic Math Block ---
:c*:{+::
SendRaw {m:}
Send {left}
return

; --- Mathematical Functions and Variables ---
:c*:{ma::
SendRaw {m:abs()}
Send {left 2}
return

:c*:{mr::
SendRaw {m:round()}
Send {left 2}
return

:c*:{mt::
SendRaw {m:trunc()}
Send {left 2}
return

:c*:{ms::
SendRaw {m:sgn()}
Send {left 2}
return

:c*:{mln::
SendRaw {m:ln()}
Send {left 2}
return

:c*:{mlog::
SendRaw {m:log()}
Send {left 2}
return

;---------------------------------
;RNG Blocks
;---------------------------------

; --- Random Blocks ---
:c*:{#(:: ; Seeded random block. Puts the cursor on the seed parameter.
SendRaw {#():}
Send {left 3}
return

:c*:{rand::
SendRaw {#:}
Send {left}
return

; --- Range Blocks ---
:c*:{rang:: ; range. Defaults to 1 for the lowest number.
SendRaw {range:1-}
Send {left}
return

:c*:{ranf:: ; rangef. Defaults to 1 for the lowest number.
SendRaw {rangef:1-}
Send {left}
return

; --- 50/50 Blocks ---
:c*:{50::
SendRaw {50:}
Send {left}
return

:c*:{%::
SendRaw {`%:}
Send {left}
return

;---------------------------------
;Time Blocks
;---------------------------------
; --- Strf Blocks ---
:c*:{strf(::
SendRaw {strf():}
Send {left}
return

; --- Strf % Time Data/Variables (You're going to love that one) ---
;	--Weekday--
; Mon - %a
:c*:%wds:: ; Weekday Short
SendRaw `%a
return

; Monday - %A
:c*:%wdf:: ; Weekday Full
SendRaw `%A
return

; 1 - %w
:c*:%wdn:: ; Weekday Number/Decimal
SendRaw `%w
return

;	--Month--
; 30 - %d
:c*:%md:: ; Month Day
SendRaw `%d
return

; 30 - %-d
:c*:%0md:: ; Zero-padded Month Day
SendRaw `%-d
return

; Sep - %b
:c*:%ms:: ; Month Short
SendRaw `%b
return

; September - %B
:c*:%mf:: ; Month Full
SendRaw `%B
return

; 9 - %m
:c*:%mn:: ; Month Number
SendRaw `%m
return

; 09 - %-m
:c*:%mn:: ; Zero-padded Month Number
SendRaw `%-m
return

;	--Year--
; 21 - %y
:c*:%ys:: ; Year Short
SendRaw `%y
return

; 2021 - %Y
:c*:%yf:: ; Year Full
SendRaw `%Y
return

;	--Hour--
; 07 - %H
:c*:%h024:: ; Zero-padded 24-hour clock Hour
SendRaw `%H
return

; 7 - %-H
:c*:%h24:: ; 24-hour clock Hour
SendRaw `%-H
return

; 07 - %I
:c*:%h012:: ; Zero-padded 12-hour clock Hour
SendRaw `%I
return

; 7 - %-I
:c*:%h12:: ; 12-hour clock Hour
SendRaw `%-I
return

; AM - %p
:c*:%am:: ; Locale’s equivalent of either AM or PM
SendRaw `%p
return

; AM - %p
:c*:%pm:: ; Locale’s equivalent of either AM or PM (just an alias of the previous one)
SendRaw `%p
return

;	--Minute--
; 06 - %M
:c*:%min:: ; Minute as a zero-padded decimal number
SendRaw `%M
return

;	--Second--
; 05 - %S
:c*:%0s:: ; Second as a zero-padded decimal number
SendRaw `%S
return

; 5 - %-S
:c*:%s:: ; Second as a decimal number
SendRaw `%-S
return

;	--Microsecond--
; 000000 - %f
:c*:%mis:: ; Microsecond as a decimal number, zero-padded on the left
SendRaw `%f
return

;	--Day of the Year--
; 273 - %j
:c*:%0yd:: ; Day of the year as a zero-padded decimal number
SendRaw `%j
return

; 273 - %-j
:c*:%yd:: ; Day of the year as a decimal number
SendRaw `%-j
return

; 273 - %j
:c*:%doty:: ; Just an alias of the previous one
SendRaw `%j
return

;	--Week number--
; 39 - %W
:c*:%wn:: ; Week number of the year (Monday as the first day of the week) as a decimal number. All days in a new year preceding the first Monday are considered to be in week 0
SendRaw `%W
return

;	--Locale's date and time representation (still in UTC)--
; Mon Sep 30 07:06:05 2021 - %c
:c*:%full:: ; Full date and time 
SendRaw `%c
return

; 09/30/13 - %x
:c*:%date:: ; Date separated by /
SendRaw `%x
return

; 07:06:05 - %X
:c*:%time:: ; Time separated by :
SendRaw `%X
return

; --- Timedelta Blocks ---
:c*:{td(:: ; td with parameter
SendRaw {td():}
Send {left 3}
return

;---------------------------------
;Manipulation Blocks
;---------------------------------

; --- Ordinal Abbreviation Blocks ---
:c*:{rd::
SendRaw {ord:}
Send {left}
return

; --- Case Blocks ---
:c*:{low::
SendRaw {lower:}
Send {left}
return

:c*:{upp::
SendRaw {upper:}
Send {left}
return

; --- Text Replacement Blocks ---
:c*:{join::
SendRaw {join():}
Send {left 3}
return

:c*:{rep::
SendRaw {replace():}
Send {left 3}
return

:c*:{url::
SendRaw {urlencode:}
Send {left}
return

:c*:{ur+::
SendRaw {urlencode(+):}
Send {left}
return

;---------------------------------
;Helpful Snippets
;---------------------------------

;Comments
:c*:{com::
SendRaw {=(comment):}
Send {left}
return

:c*:{COM::
SendRaw, {=(COMMENT):}
Send {left}
return

;Get the number of words in args and define it as a variable
:c*:{len::
SendRaw {=(Length):{index(&$):{args} &$}}
Send {enter}
return

;Make the first word of args all lowercase (helpful for standardising input)
:c*:{l1::
SendRaw {=(L1):{lower:{1}}}
Send {Enter}
return

;Make the entirety of args all lowercase (helpful for standardising input)
:c*:{larg::
SendRaw {=(Largs):{lower:{args}}}
Send {Enter}
return
;Make the first word of args all uppercase (helpful for standardising input)
:c*:{u1::
SendRaw {=(U1):{upper:{1}}}
Send {Enter}
return

;Make the entirety of args all uppercase (helpful for standardising input)
:c*:{larg::
SendRaw {=(Uargs):{upper:{args}}}
Send {Enter}
return

;Outputs "true" if args is a number, outputs "false" otherwise
:c*:{isnum::
SendRaw {in({m:sgn({args})}):-1 0 1}
return

;Converts the current time (or any time in unix form) to any time zone
:c*:{timezone::
SendRaw {=(offset):}
Send {Enter}
SendRaw {=(hins):3600}
Send {Enter}
SendRaw {=(output):{strf({m:trunc({unix}+({hins}*{offset}))}):`%-I:`%M `%p}}
Send {Up 2}
Send {End}
Send {Left}
return

;Generates a random color
:c*:{randhex::
SendRaw {=(i):#:A,B,C,D,E,F,0,1,2,3,4,5,6,7,8,9}
Send {Enter}
SendRaw {=(randomhex):{{i}}{{i}}{{i}}{{i}}{{i}}{{i}}}
return

;Sets the embed color to a random color
:c*:{randemc::
SendRaw {=(i):#:A,B,C,D,E,F,0,1,2,3,4,5,6,7,8,9}
Send {Enter}
SendRaw {embed(color):#{{i}}{{i}}{{i}}{{i}}{{i}}{{i}}}
return

;Test if {args(1)} is a valid hex color
:c*:{ishex::
SendRaw {=(uargs):{replace(#,):{upper:{args(1)}}}}
Send {Enter}
SendRaw {=(length):{index(`%^&):{replace(, ):{uargs}} `%^&}}
Send {Enter}
SendRaw {=(hex2num):{replace(A,10):{replace(B,11):{replace(C,12):{replace(D,13):{replace(E,14):{replace(F,15):{uargs}}}}}}}}
Send {Enter}
SendRaw {=(hextest):{m:trunc({join(+):{replace(, ):{hex2num}}})}}
Send {Enter 2}
SendRaw {=(error):#{uargs}}
Send {Enter}
SendRaw {=(error1):There are 6 characters in a Hexidecimal Color Code (no alpha values), try again.}
Send {Enter}
SendRaw {=(error2):Hexidecimal Color Codes should only contain digits 0-9 and letters A-F, there is an invalid character present, try again.}
Send {Enter 2}
SendRaw {error{if({length}!=6):1|{if({hextest}!={m:trunc({hextest}/1)}):2}}}
return

;Add a cooldown role to the user
:c*:{cooldown::
SendRaw {=(cdRole):RoleIDHere}
Send {Enter}
SendRaw {=(cdTime):5m}
Send {Enter}
SendRaw {blacklist(You need to wait {cdTime} before using the command again.):{cdRole}}
Send {Enter}
SendRaw {override}{silence}
Send {Enter}
SendRaw {c:temprole {user(id)} {cdTime} {cdRole}}
Send {Up 5}
Send {End}
Send {Left}
return

;Capitalize the first letter of each word in args
:c*:{firstcap::
SendRaw {replace( z, Z):{replace( y, Y):{replace( x, X):{replace( w, W):{replace( v, V):{replace( u, U):{replace( t, T):{replace( s, S):{replace( r, R):{replace( q, Q):{replace( p, P):{replace( o, O):{replace( n, N):{replace( m, M):{replace( l, L):{replace( k, K):{replace( j, J):{replace( i, I):{replace( h, H):{replace( g, G):{replace( f, F):{replace( e, E):{replace( d, D):{replace( c, C):{replace( b, B):{replace( a, A): {args}}}}}}}}}}}}}}}}}}}}}}}}}}}
return

;Count the instances of a character in args (character can't be a comma, parentheses, or curly brackets)
:c*:{count::
SendRaw {=(charactertocount):}
Send {Enter}
SendRaw {=(arglength):{index($`%&):{args} $`%&}}
Send {Enter}
SendRaw {=(newarglength):{index($`%&):{replace({charactertocount},. .):{args}} $`%&}}
Send {Enter}
SendRaw {=(charactercount):{m:trunc({newarglength}-{arglength})}}
Send {Enter}
SendRaw {charactercount} `{charactertocount}` in the args
Send {Up 5}
Send {End}
Send {Left}
return

;Outputs a target mention, even if args is the target's id
:c*:{idmen::
SendRaw {if({in(@):{args}}==true):{args}|<@{args}>}
return

;Get an animated server icon (use {icon} instead of {server(icon)} in your tag)
:c*:{aicon::
SendRaw {=(icon):{if({in(a_):{server(icon)}}==true):{replace(png,gif):{server(icon)}}|{server(icon)}}}
return

;Round to the nearest number
:c*:{round::
SendRaw {=(numtoround):}
Send {Enter}
SendRaw {=(decplace):3}
Send {Enter}
SendRaw {m:round({num}*(10^{decplace}))/(10^{decplace})}
Send {Up 2}
Send {End}
Send {Left}
return

;Send an embed conditionally
:c*:{embedcond::
SendRaw {=():}
Send {Enter}
SendRaw {{if(boolean):blacklist(Error message that will be send instead of the embed):{server(id)}}}
Send {Home}
Send {Right 5}
return

;Switch method
:c*:{switch::
SendRaw {=(l1):{lower:{1}}}
Send {Enter}
SendRaw {=({l1}):Error message here}
Send {Enter}
SendRaw {=():Output for first variable}
Send {Enter}
SendRaw {=():Output for second variable}
Send {Enter}
SendRaw {=():Output for third variable}
Send {Enter}
SendRaw {{l1}}
return