;x----------------------------------------------------------
;Automatically generated by AutoHotkey. You can ignore that, but you should keep it nonetheless.
;----------------------------------------------------------
#NoEnv  ; Recommended for performance and compatibility with future AutoHotkey releases.
; #Warn  ; Enable warnings to assist with detecting common errors.
SendMode Input  ; Recommended for new scripts due to its superior speed and reliability.
SetWorkingDir %A_ScriptDir%  ; Ensures a consistent starting directory.
;----------------------------------------------------------

;----------------------------------------------------------
;Carl-bot's TagScript IntelliSense/Macro Script by Asty' and LPB
;Based on the blocks at: https://docs.carl.gg/tags-and-triggers/tags-advanced-Keyword/
;----------------------------------------------------------

;---------------------------------
;Command Block (annoyingly needs to be at the top)
;---------------------------------
Hotstring( ":xc*:`{c`:", "commandblock")
Return

commandblock:
SendRaw, {c:}
Send {left}
Return

;---------------------------------
;Discord Objects
;---------------------------------

; --- {user} Object ---
:C*:{user::
SendRaw {user}
Return

:C*:{uav::
SendRaw {user(avatar)}
Return

:C*:{uid::
SendRaw {user(id)}
Return

:C*:{umen::
SendRaw {user(mention)}
Return

:C*:{ucat::
SendRaw {user(created_at)}
Return

:C*:{ujat::
SendRaw {user(joined_at)}
Return

:C*:{uco::
SendRaw {user(color)}
Return

:C*:{uname::
SendRaw {user(name)}
Return

:C*:{uprop::
SendRaw {user(proper)}
Return

:C*:{uroles::
SendRaw {user(roleids)}
Return

:C*:{urid::
SendRaw {user(roleids)}
Return

:C*:{upos::
SendRaw {user(position)}
Return

; --- {target} Object ---
:C*:{tar::
SendRaw {target}
Return

:C*:{tav::
SendRaw {target(avatar)}
Return

:C*:{tid::
SendRaw {target(id)}
Return

:C*:{tmen::
SendRaw {target(mention)}
Return

:C*:{tcat::
SendRaw {target(created_at)}
Return

:C*:{tjat::
SendRaw {target(joined_at)}
Return

:C*:{tco::
SendRaw {target(color)}
Return

:C*:{tname::
SendRaw {target(name)}
Return

:C*:{tprop::
SendRaw {target(proper)}
Return

:C*:{troles::
SendRaw {target(roleids)}
Return

:C*:{trid::
SendRaw {target(roleids)}
Return

:C*:{tpos::
SendRaw {target(position)}
Return

; --- {server} Object---
:C*:{ser::
SendRaw {server}
Return

:C*:{sic::
SendRaw {server(icon)}
Return

:C*:{sav::
SendRaw {server(icon)}
Return

:C*:{sid::
SendRaw {server(id)}
Return

:C*:{sown::
SendRaw {server(owner)}
Return

:C*:{sran::
SendRaw {server(random)}
Return

:C*:{smem::
SendRaw {server(members)}
Return

:C*:{shum::
SendRaw {server(humans)}
Return

:C*:{sro::
SendRaw {server(roles)}
Return

:C*:{sch::
SendRaw {server(channels)}
Return

:C*:{scat::
SendRaw {server(created_at)}
Return

; --- {channel} Object ---
:C*:{chan::
SendRaw {channel}
Return

:C*:{cid::
SendRaw {channel(id)}
Return

:C*:{ct::
SendRaw {channel(topic)}
Return

:C*:{csm::
SendRaw {channel(slowmode)}
Return

:C*:{cpos::
SendRaw {channel(position)}
Return

:C*:{cm::
SendRaw {channel(mention)}
Return

;---------------------------------
;Action Blocks
;---------------------------------

:C*:{del::
SendRaw {delete}
Return

:C*:{sil::
SendRaw {silence}
Return

:C*:{ov::
SendRaw {override}
Return

;---------------------------------
;Redirection Blocks
;---------------------------------

:C*:{dm::
SendRaw {dm}
Return

:C*:{red::
SendRaw {redirect:}
Send {Left}
Return

;---------------------------------
;Use Limiting Blocks
;---------------------------------

:C*:{req::
SendRaw {require():}
Send, {Left 3}
Return

:C*:{bl::
SendRaw {blacklist():}
Send, {Left 3}
Return

;---------------------------------
;Reaction Blocks
;---------------------------------

:C*:{rea::
SendRaw {react: }
Send {Left}
Return

:C*:{reu::
SendRaw {reactu: }
Send {Left}
Return

;---------------------------------
;Specific Command Blocks
;---------------------------------

:C*:{crole:: ; Command Role - Role User ID Block
SendRaw {c:role {user(id)} }
Send {Left}
Return

:C*:{cra:: ; Command Role Add - Role Add User ID Block
SendRaw {c:role add {user(id)} }
Send {Left}
Return

:C*:{crt:: ;  Command Role Target - Role Add Target ID Block
SendRaw {c:role add {target(id)} }
Send {Left}
Return

:C*:{crc:: ; Command Role Custom
SendRaw {c:role custom {user(id)} }
Send {Left}
Return

:C*:{cec:: ; Command Echo
SendRaw {c:echo }
Send {Left}
Return

:C*:{cem:: ; Command Cembed
SendRaw {c:cembed }
Send {left}
Return

:C*:{cfeed:: ; Command Announce to Feed
SendRaw {override}
Send {enter}
SendRaw {c:feed announce }
Send {Left}
Return
;---------------------------------
;Condition Blocks
;---------------------------------

:C*:{if::
SendRaw {if():}
Send {Left 3}
Return

:C*:{any::
SendRaw {any(|):}
Send {Left 4}
Return

:C*:{or::
SendRaw {or(|):}
Send {Left 4}
Return

:C*:{all::
SendRaw {all(|):}
Send {Left 4}
Return

:C*:{and::
SendRaw {and(|):}
Send {Left 4}
Return

:C*:{break::
SendRaw {break():}
Send {left 3}
Return

;---------------------------------
;Variable Blocks (Data Storage)
;---------------------------------

:C*:{=::
SendRaw {=():}
Send {left 2}
Return

:C*:{var::
SendRaw {var():}
Send {left 2}
Return

:C*:{let::
SendRaw {let():}
Send {left 2}
Return

;---------------------------------
;Arguments (Parsing)
;---------------------------------

:C*:{arg(::
SendRaw {args()}
Send {left 2}
Return

:C*:{args::
SendRaw {args}
Return

;---------------------------------
;List and Cycle Blocks
;---------------------------------

:C*:{li::
SendRaw {list():}
Send {left 3}
Return

:C*:{cy::
SendRaw {cycle():}
Send {left 3}
Return

:C*:{dex::
SendRaw {index():}
Send {left 3}
Return

;---------------------------------
;Membership Test Operations (In and Contains)
;---------------------------------

:C*:{in::
SendRaw {in():}
Send {left 3}
Return

:C*:{con::
SendRaw {contains():}
Send {left 3}
Return

;---------------------------------
;Embed Blocks
;---------------------------------

:C*:{emt::
SendRaw {embed(title):}
Send {left}
Return

:C*:{emu::
SendRaw {embed(url):new title url}
Send {left}
Return

:C*:{emd::
SendRaw {embed(description):}
Send {left}
Return

:C*:{emc::
SendRaw {embed(color):#}
Send {left}
Return

:C*:{emn::
SendRaw {embed(timestamp):now}
Send {left}
Return

;---------------------------------
;Math Blocks
;---------------------------------

; --- Basic Math Block ---
:C*:{+::
SendRaw {m:}
Send {left}
Return

; --- Mathematical Functions and Variables ---
:C*:{ma::
SendRaw {m:abs()}
Send {left 2}
Return

:C*:{mr::
SendRaw {m:round()}
Send {left 2}
Return

:C*:{mt::
SendRaw {m:trunc()}
Send {left 2}
Return

:C*:{ms::
SendRaw {m:sgn()}
Send {left 2}
Return

:C*:{mln::
SendRaw {m:ln()}
Send {left 2}
Return

:C*:{mlog::
SendRaw {m:log()}
Send {left 2}
Return

;---------------------------------
;RNG Blocks
;---------------------------------

; --- Random Blocks ---
:C*:{#(:: ; Seeded random block. Puts the cursor on the seed parameter.
SendRaw {#():}
Send {left 3}
Return

:C*:{rand::
SendRaw {#:}
Send {left}
Return

; --- Range Blocks ---
:C*:{rang:: ; range. Defaults to 1 for the lowest number.
SendRaw {range:1-}
Send {left}
Return

:C*:{ranf:: ; rangef. Defaults to 1 for the lowest number.
SendRaw {rangef:1-}
Send {left}
Return

; --- 50/50 Blocks ---
:C*:{50::
SendRaw {50:}
Send {left}
Return

:C*:{?::
SendRaw {?:}
Send {left}
Return

;---------------------------------
;Time Blocks
;---------------------------------
; --- Strf Blocks ---
:C*:{strf(::
SendRaw {strf():}
Send {left}
Return

; --- Strf % Time Data/Variables (You're going to love that one) ---
;	--Weekday--
; Mon - %a
:C*:%wds:: ; Weekday Short
SendRaw `%a
Return

; Monday - %A
:C*:%wdf:: ; Weekday Full
SendRaw `%A
Return

; 1 - %w
:C*:%wdn:: ; Weekday Number/Decimal
SendRaw `%w
Return

;	--Month--
; 30 - %d
:C*:%md:: ; Month Day
SendRaw `%d
Return

; 30 - %-d
:C*:%0md:: ; Zero-padded Month Day
SendRaw `%-d
Return

; Sep - %b
:C*:%ms:: ; Month Short
SendRaw `%b
Return

; September - %B
:C*:%mf:: ; Month Full
SendRaw `%B
Return

; 9 - %m
:C*:%mn:: ; Month Number
SendRaw `%m
Return

; 09 - %-m
:C*:%0mn:: ; Zero-padded Month Number
SendRaw `%-m
Return

;	--Year--
; 21 - %y
:C*:%ys:: ; Year Short
SendRaw `%y
Return

; 2021 - %Y
:C*:%yf:: ; Year Full
SendRaw `%Y
Return

;	--Hour--
; 07 - %H
:C*:%h024:: ; Zero-padded 24-hour clock Hour
SendRaw `%H
Return

; 7 - %-H
:C*:%h24:: ; 24-hour clock Hour
SendRaw `%-H
Return

; 07 - %I
:C*:%h012:: ; Zero-padded 12-hour clock Hour
SendRaw `%I
Return

; 7 - %-I
:C*:%h12:: ; 12-hour clock Hour
SendRaw `%-I
Return

; AM - %p
:C*:%am:: ; Locale’s equivalent of either AM or PM
SendRaw `%p
Return

; AM - %p
:C*:%pm:: ; Locale’s equivalent of either AM or PM (just an alias of the previous one)
SendRaw `%p
Return

;	--Minute--
; 06 - %M
:C*:%min:: ; Minute as a zero-padded decimal number
SendRaw `%M
Return

;	--Second--
; 05 - %S
:C*:%0sec:: ; Second as a zero-padded decimal number
SendRaw `%S
Return

; 5 - %-S
:C*:%sec:: ; Second as a decimal number
SendRaw `%-S
Return

;	--Microsecond--
; 000000 - %f
:C*:%mis:: ; Microsecond as a decimal number, zero-padded on the left
SendRaw `%f
Return

;	--Day of the Year--
; 273 - %j
:C*:%0yd:: ; Day of the year as a zero-padded decimal number
SendRaw `%j
Return

; 273 - %-j
:C*:%yd:: ; Day of the year as a decimal number
SendRaw `%-j
Return

; 273 - %-j
:C*:%doty:: ; Just an alias of the previous one
SendRaw `%-j
Return

;	--Week number--
; 39 - %W
:C*:%wn:: ; Week number of the year (Monday as the first day of the week) as a decimal number. All days in a new year preceding the first Monday are considered to be in week 0
SendRaw `%W
Return

;	--Locale's date and time representation (still in UTC)--
; Mon Sep 30 07:06:05 2021 - %c
:C*:%full:: ; Full date and time 
SendRaw `%c
Return

; 09/30/13 - %x
:C*:%date:: ; Date separated by /
SendRaw `%x
Return

; 07:06:05 - %X
:C*:%time:: ; Time separated by :
SendRaw `%X
Return

; --- Timedelta Blocks ---
:C*:{td(:: ; td with parameter
SendRaw {td():}
Send {left 3}
Return

;---------------------------------
;Manipulation Blocks
;---------------------------------

; --- Ordinal Abbreviation Blocks ---
:C*:{rd::
SendRaw {ord:}
Send {left}
Return

; --- Case Blocks ---
:C*:{low::
SendRaw {lower:}
Send {left}
Return

:C*:{upp::
SendRaw {upper:}
Send {left}
Return

; --- Text Replacement Blocks ---
:C*:{join::
SendRaw {join():}
Send {left 3}
Return

:C*:{rep::
SendRaw {replace():}
Send {left 3}
Return

:C*:{url::
SendRaw {urlencode:}
Send {left}
Return

:C*:{ur+::
SendRaw {urlencode(+):}
Send {left}
Return

;---------------------------------
;Helpful Snippets
;---------------------------------

;Comments
:C*:{com::
SendRaw {=(comment):}
Send {left}
Return

:C*:{COM::
SendRaw, {=(COMMENT):}
Send {left}
Return

;Get the number of words in args and define it as a variable
:C*:{len::
SendRaw {=(Length):{index(&$):{args} &$}}
Send {enter}
Return

;Make the first word of args all lowercase (helpful for standardising input)
:C*:{l1::
SendRaw {=(L1):{lower:{1}}}
Send {enter}
Return

;Make the entirety of args all lowercase (helpful for standardising input)
:C*:{larg::
SendRaw {=(Largs):{lower:{args}}}
Send {enter}
Return

;Make the first word of args all uppercase (helpful for standardising input)
:C*:{u1::
SendRaw {=(U1):{upper:{1}}}
Send {enter}
Return

;Make the entirety of args all uppercase (helpful for standardising input)
:C*:{uarg::
SendRaw {=(Uargs):{upper:{args}}}
Send {enter}
Return

;Outputs "true" if args is a number, outputs "false" otherwise
:C*:{isnum::
SendRaw {in({m:sgn({args})}):-1 0 1}
Return

;Converts the current time (or any time in unix form) to any time zone
:C*:{timezone::
SendRaw {=(offset):}
Send {enter}
SendRaw {=(hins):3600}
Send {enter}
SendRaw {=(output):{strf({m:trunc({unix}+({hins}*{offset}))}):`%-I:`%M `%p}}
Send {Up 2}
Send {End}
Send {left}
Return

;Generates a random color
:C*:{rcol::
SendRaw {=(i):#:A,B,C,D,E,F,0,1,2,3,4,5,6,7,8,9}
Send {enter}
SendRaw {=(randomhex):{{i}}{{i}}{{i}}{{i}}{{i}}{{i}}}
Return

;Sets the embed color to a random color
:C*:{remb::
SendRaw {=(i):#:A,B,C,D,E,F,0,1,2,3,4,5,6,7,8,9}
Send {enter}
SendRaw {embed(color):#{{i}}{{i}}{{i}}{{i}}{{i}}{{i}}}
Return

;Test if {args(1)} is a valid hex color
:C*:{ishex::
Goto hextest
Return
:C*:{hextest::
Goto hextest
Return
hextest:
SendRaw {=(uargs):{replace(#,):{upper:{args(1)}}}}
Send {enter}
SendRaw {=(length):{index(`%^&):{replace(, ):{uargs}} `%^&}}
Send {enter}
SendRaw {=(hex2num):{replace(A,10):{replace(B,11):{replace(C,12):{replace(D,13):{replace(E,14):{replace(F,15):{uargs}}}}}}}}
Send {enter}
SendRaw {=(hextest):{m:trunc({join(+):{replace(, ):{hex2num}}})}}
Send {Enter 2}
SendRaw {=(error):#{uargs}}
Send {enter}
SendRaw {=(error1):There are 6 characters in a Hexidecimal Color Code (no alpha values), try again.}
Send {enter}
SendRaw {=(error2):Hexidecimal Color Codes should only contain digits 0-9 and letters A-F, there is an invalid character present, try again.}
Send {Enter 2}
SendRaw {error{if({length}!=6):1|{if({hextest}!={m:trunc({hextest}/1)}):2}}}
Return

;Add a cooldown role to the user
:C*:{cooldown::
SendRaw {=(cdRole):RoleIDHere}
Send {enter}
SendRaw {=(cdTime):5m}
Send {enter}
SendRaw {blacklist(You need to wait {cdTime} before using the command again.):{cdRole}}
Send {enter}
SendRaw {override}{silence}
Send {enter}
SendRaw {c:temprole {user(id)} {cdTime} {cdRole}}
Send {Up 5}
Send {End}
Send {left}
Return

;Capitalize the first letter of each word in args
:C*:{firstcap::
SendRaw {replace( z, Z):{replace( y, Y):{replace( x, X):{replace( w, W):{replace( v, V):{replace( u, U):{replace( t, T):{replace( s, S):{replace( r, R):{replace( q, Q):{replace( p, P):{replace( o, O):{replace( n, N):{replace( m, M):{replace( l, L):{replace( k, K):{replace( j, J):{replace( i, I):{replace( h, H):{replace( g, G):{replace( f, F):{replace( e, E):{replace( d, D):{replace( c, C):{replace( b, B):{replace( a, A): {args}}}}}}}}}}}}}}}}}}}}}}}}}}}
Return

;Count the instances of a character in args (character can't be a comma, parentheses, or curly brackets)
:C*:{count::
SendRaw {=(charactertocount):}
Send {enter}
SendRaw {=(arglength):{index($`%&):{args} $`%&}}
Send {enter}
SendRaw {=(newarglength):{index($`%&):{replace({charactertocount},. .):{args}} $`%&}}
Send {enter}
SendRaw {=(charactercount):{m:trunc({newarglength}-{arglength})}}
Send {enter}
SendRaw {charactercount} `{charactertocount}` in the args
Send {Up 5}
Send {End}
Send {left}
Return

;Outputs a target mention, even if args is the target's id
:C*:{idmen::
SendRaw {if({in(@):{args}}==true):{args}|<@{args}>}
Return

;Get an animated server icon (use {icon} instead of {server(icon)} in your tag)
:C*:{aicon::
SendRaw {if({in(a_):{server(icon)}}==true):{replace(png,gif):{server(icon)}}|{server(icon)}}
Return

;Round to the nearest number
:C*:{round::
SendRaw {=(number):}
Send {enter}
SendRaw {=(decimal):3}
Send {enter}
SendRaw {m:round({num}*(10^{number}))/(10^{decimal})}
Send {Up 2}
Send {End}
Send {left}
Return

;Send an embed conditionally
:C*:{embedcond::
SendRaw {=():}
Send {enter}
SendRaw {{if(boolean):blacklist(Error message that will be send instead of the embed):{server(id)}}}
Send {Home}
Send {Right 5}
Return

;Switch method
:C*:{switch::
SendRaw {=(L1):{lower:{1}}}
Send {enter}
SendRaw {=({L1}):Error message here}
Send {enter}
SendRaw {=():Output for first variable}
Send {enter}
SendRaw {=():Output for second variable}
Send {enter}
SendRaw {=():Output for third variable}
Send {enter}
SendRaw {{L1}}
Return

;Add commas in numbers
:C*:{numcomma::
SendRaw {replace(st,):{replace(nd,):{replace(rd,):{replace(th,):{ord:{args}}}}}}
Return